Repository Lucky-Vicky-PetHarmony/Server, pull requests merged in 2024-08, with the labels that each got.

#11 게시판 기능 구현 (등록, 수정, 리스트 필터링, 삭제)
  src/main/java/luckyvicky/petharmony/controller/BoardController.java
  src/main/java/luckyvicky/petharmony/controller/CommentController.java
  src/main/java/luckyvicky/petharmony/dto/board/BoardDeleteDTO.java
  src/main/java/luckyvicky/petharmony/dto/board/BoardDetailRequestDTO.java
  src/main/java/luckyvicky/petharmony/dto/board/BoardDetailResponseDTO.java
  src/main/java/luckyvicky/petharmony/dto/board/BoardListRequestDTO.java
  src/main/java/luckyvicky/petharmony/dto/board/BoardListResponseDTO.java
  src/main/java/luckyvicky/petharmony/dto/board/BoardPostDTO.java
  src/main/java/luckyvicky/petharmony/dto/board/BoardUpdateDTO.java
  src/main/java/luckyvicky/petharmony/dto/comment/CommentPostDTO.java
  src/main/java/luckyvicky/petharmony/dto/comment/CommentResponseDTO.java
  src/main/java/luckyvicky/petharmony/dto/comment/CommentUpdateDTO.java
  src/main/java/luckyvicky/petharmony/entity/board/Board.java
  src/main/java/luckyvicky/petharmony/entity/board/Comment.java
  src/main/java/luckyvicky/petharmony/entity/board/Image.java
  src/main/java/luckyvicky/petharmony/repository/BoardRepository.java
  src/main/java/luckyvicky/petharmony/repository/CommentRepository.java
  src/main/java/luckyvicky/petharmony/repository/ImageRepository.java
  src/main/java/luckyvicky/petharmony/service/BoardService.java
  src/main/java/luckyvicky/petharmony/service/BoardServiceImpl.java
  src/main/java/luckyvicky/petharmony/service/CommentService.java
  src/main/java/luckyvicky/petharmony/service/CommentServiceImpl.java
  src/main/java/luckyvicky/petharmony/service/ImageService.java
  src/main/java/luckyvicky/petharmony/service/ImageServiceImpl.java
  src/main/java/luckyvicky/petharmony/service/S3Service.java
  src/main/java/luckyvicky/petharmony/service/S3ServiceImpl.java
Labels: 💡 feat, 🐥 chore, 🌈 refactor

#12 feat: 게시글 검색 및 정렬 기능 추가 및 수정
  src/main/java/luckyvicky/petharmony/controller/BoardController.java
  src/main/java/luckyvicky/petharmony/entity/board/Board.java
  src/main/java/luckyvicky/petharmony/repository/BoardRepository.java
  src/main/java/luckyvicky/petharmony/service/BoardService.java
  src/main/java/luckyvicky/petharmony/service/BoardServiceImpl.java
Labels: 💡 feat

#13 카카오 로그인
  build.gradle
  src/main/java/luckyvicky/petharmony/config/WebConfig.java
  src/main/java/luckyvicky/petharmony/controller/UserController.java
  src/main/java/luckyvicky/petharmony/dto/user/KakaoAccountDTO.java
  src/main/java/luckyvicky/petharmony/dto/user/KakaoInfoDTO.java
  src/main/java/luckyvicky/petharmony/dto/user/KakaoLogInResponseDTO.java
  src/main/java/luckyvicky/petharmony/entity/User.java
  src/main/java/luckyvicky/petharmony/repository/UserRepository.java
  src/main/java/luckyvicky/petharmony/security/SecurityConfig.java
  src/main/java/luckyvicky/petharmony/service/UserService.java
  src/main/java/luckyvicky/petharmony/service/UserServiceImpl.java
  src/main/resources/application.properties
Labels: 💡 feat, 🏗️ build

#18 [구현중] 마이페이지
  src/main/java/luckyvicky/petharmony/controller/MyPageController.java
  src/main/java/luckyvicky/petharmony/controller/UserController.java
  src/main/java/luckyvicky/petharmony/dto/mypage/MyProfileRequestDTO.java
  src/main/java/luckyvicky/petharmony/dto/mypage/MyProfileResponseDTO.java
  src/main/java/luckyvicky/petharmony/dto/mypage/PasswordRequestDTO.java
  src/main/java/luckyvicky/petharmony/dto/user/FindIdResponseDTO.java
  src/main/java/luckyvicky/petharmony/dto/user/KakaoAccountDTO.java
  src/main/java/luckyvicky/petharmony/dto/user/LogInResponseDTO.java
  src/main/java/luckyvicky/petharmony/entity/User.java
  src/main/java/luckyvicky/petharmony/repository/BoardPinRepository.java
  src/main/java/luckyvicky/petharmony/service/MyPageService.java
  src/main/java/luckyvicky/petharmony/service/MyPageServiceImpl.java
  src/main/java/luckyvicky/petharmony/service/UserService.java
  src/main/java/luckyvicky/petharmony/service/UserServiceImpl.java
Labels: 💡 feat, 🛠️ fix, 🐥 chore

#19 신고목록과 필터링, 신고상세보기, 신고처리기능 추가
  src/main/java/luckyvicky/petharmony/controller/BoardController.java
  src/main/java/luckyvicky/petharmony/controller/ReportController.java
  src/main/java/luckyvicky/petharmony/dto/board/BoardDetailResponseDTO.java
  src/main/java/luckyvicky/petharmony/dto/comment/CommentResponseDTO.java
  src/main/java/luckyvicky/petharmony/dto/report/ReportDetailDTO.java
  src/main/java/luckyvicky/petharmony/dto/report/ReportDetailListDTO.java
  src/main/java/luckyvicky/petharmony/dto/report/ReportListResponseDTO.java
  src/main/java/luckyvicky/petharmony/dto/report/ReportPostDTO.java
  src/main/java/luckyvicky/petharmony/entity/User.java
  src/main/java/luckyvicky/petharmony/entity/board/Board.java
  src/main/java/luckyvicky/petharmony/entity/board/BoardPin.java
  src/main/java/luckyvicky/petharmony/entity/board/Comment.java
  src/main/java/luckyvicky/petharmony/entity/board/Image.java
  src/main/java/luckyvicky/petharmony/entity/board/Report.java
  src/main/java/luckyvicky/petharmony/repository/BoardPinRepository.java
  src/main/java/luckyvicky/petharmony/repository/BoardRepository.java
  src/main/java/luckyvicky/petharmony/repository/CommentRepository.java
  src/main/java/luckyvicky/petharmony/repository/ReportRepository.java
  src/main/java/luckyvicky/petharmony/service/BoardService.java
  src/main/java/luckyvicky/petharmony/service/BoardServiceImpl.java
  src/main/java/luckyvicky/petharmony/service/CommentService.java
  src/main/java/luckyvicky/petharmony/service/CommentServiceImpl.java
  src/main/java/luckyvicky/petharmony/service/ReportService.java
  src/main/java/luckyvicky/petharmony/service/ReportServiceImpl.java
  src/main/java/luckyvicky/petharmony/service/S3Service.java
Labels: 💡 feat, 🐥 chore, 🌈 refactor

#20 feat: 신고 처리에 따라 회원정지, 회원탈퇴여부 저장
  src/main/java/luckyvicky/petharmony/config/WebConfig.java
  src/main/java/luckyvicky/petharmony/entity/User.java
  src/main/java/luckyvicky/petharmony/entity/board/ReportProcess.java
  src/main/java/luckyvicky/petharmony/service/ReportServiceImpl.java
Labels: 💡 feat

#21 [구현중] 마이페이지
  src/main/java/luckyvicky/petharmony/controller/MyPageController.java
  src/main/java/luckyvicky/petharmony/dto/mypage/MyCommentsDTO.java
  src/main/java/luckyvicky/petharmony/repository/BoardRepository.java
  src/main/java/luckyvicky/petharmony/repository/CommentRepository.java
  src/main/java/luckyvicky/petharmony/service/MyPageService.java
  src/main/java/luckyvicky/petharmony/service/MyPageServiceImpl.java
Labels: 💡 feat, 🐥 chore

#23 게시판, 신고목록 디테일한 부분 수정
  src/main/java/luckyvicky/petharmony/controller/BoardController.java
  src/main/java/luckyvicky/petharmony/controller/CommentController.java
  src/main/java/luckyvicky/petharmony/controller/ReportController.java
  src/main/java/luckyvicky/petharmony/dto/user/LogInResponseDTO.java
  src/main/java/luckyvicky/petharmony/entity/board/Board.java
  src/main/java/luckyvicky/petharmony/repository/BoardPinRepository.java
  src/main/java/luckyvicky/petharmony/repository/CommentRepository.java
  src/main/java/luckyvicky/petharmony/service/BoardPinServiceImpl.java
  src/main/java/luckyvicky/petharmony/service/BoardServiceImpl.java
  src/main/java/luckyvicky/petharmony/service/CommentServiceImpl.java
  src/main/java/luckyvicky/petharmony/service/UserServiceImpl.java
Labels: 🐥 chore

#32 메인페이지 슬라이드
  src/main/java/luckyvicky/petharmony/controller/MainController.java
  src/main/java/luckyvicky/petharmony/dto/main/SlideResponseDTO.java
  src/main/java/luckyvicky/petharmony/repository/PetInfoRepository.java
  src/main/java/luckyvicky/petharmony/service/MainService.java
  src/main/java/luckyvicky/petharmony/service/MainServiceImpl.java
Labels: 💡 feat

#33 메인 페이지 엔드포인트
  src/main/java/luckyvicky/petharmony/controller/MainController.java
  src/main/java/luckyvicky/petharmony/dto/main/PetCardResponseDTO.java
  src/main/java/luckyvicky/petharmony/repository/PetInfoRepository.java
  src/main/java/luckyvicky/petharmony/service/MainService.java
  src/main/java/luckyvicky/petharmony/service/MainServiceImpl.java
Labels: 💡 feat, 🌈 refactor

#39 chore: 기존 입양 동물 관련 DTO, Service, Controller 수정
  src/main/java/luckyvicky/petharmony/controller/MainController.java
  src/main/java/luckyvicky/petharmony/controller/MyPageController.java
  src/main/java/luckyvicky/petharmony/dto/main/PetCardResponseDTO.java
  src/main/java/luckyvicky/petharmony/dto/main/SlideResponseDTO.java
  src/main/java/luckyvicky/petharmony/dto/mypage/MyInterestedPetDTO.java
  src/main/java/luckyvicky/petharmony/repository/PetInfoRepository.java
  src/main/java/luckyvicky/petharmony/repository/PetLikeRepository.java
  src/main/java/luckyvicky/petharmony/service/MainServiceImpl.java
  src/main/java/luckyvicky/petharmony/service/MyPageService.java
  src/main/java/luckyvicky/petharmony/service/MyPageServiceImpl.java
  src/main/java/luckyvicky/petharmony/service/PetInfoFormatService.java
Labels: 🐥 chore
